# **2. DERS: array(), Built in Function**

In [3]:
import numpy as np

## ndim ve ndmin 

ndim -> number of dimension
- oluşturulan array'in kaç boyutlu olduğunu gösterir

ndmin --> minimum dimension
- oluşturulan array'ın kaç boyutlu olacağını belirler

In [6]:
arr0 = np.array(5)
arr0

array(5)

In [5]:
arr0.ndim       # arr0 bir scaler'dir yani sıfır boyutludur

0

In [8]:
arr1 = np.array([1, 2])
arr1

array([1, 2])

In [9]:
arr1.ndim

1

In [11]:
my_list = list(range(0, 24))

In [13]:
my_array = np.array(my_list)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [14]:
my_array2 = np.array(my_list, ndmin=2)      # array'in 2 boyutlu olacağına karar verdik
my_array2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23]])

In [15]:
my_array2.ndim

2

In [18]:
my_array.shape      # tek boyutlu 

(24,)

In [19]:
my_array2.shape     # 2 boyutlu 

(1, 24)

## dtype and astype()

dtype
- oluşturduumuz array'ın taypını belirlediği gibi, göstermeye de yarar

astype()
- bir array'in type'ını değiştirir

In [20]:
# int8 -> 8bitlik bir integer'dır ve 1byte'a denk gelir.
# int64 -> 64bitlik bir integer'dır ve 8byte'a denk gelir.
# float128 -> 128bitlik bir float'tır ve 16byte'a denk gelir
# complex256
# uint16 

# vs vs...

In [21]:
my_int = np.array([1, 2, 3])
my_int

array([1, 2, 3])

In [22]:
my_int.dtype

dtype('int32')

In [23]:
my_int = np.array([1, 2, 3], dtype="int64")
my_int

array([1, 2, 3], dtype=int64)

In [24]:
my_float = np.array([1, 2, 3, 4.5])
my_float

array([1. , 2. , 3. , 4.5])

In [28]:
my_float.dtype

dtype('float64')

In [30]:
my_string = np.array(["emre", "çakır", 1, 2, 3, 5.2])
my_string   # hepsi string eleman'a dönüştü

array(['emre', 'çakır', '1', '2', '3', '5.2'], dtype='<U32')

In [31]:
my_string.dtype 

dtype('<U32')

In [33]:
my_float2 = np.array([1, 2, 3], dtype="float")
my_float2

array([1., 2., 3.])

In [35]:
my_float2.astype("int") # yeni bir değişkene atamalıyız

array([1, 2, 3])

In [36]:
my_float2

array([1., 2., 3.])

In [37]:
new_int = my_float2.astype("int")
new_int

array([1, 2, 3])

In [38]:
new_int.dtype

dtype('int32')

In [39]:
new_bool = my_float2.astype("bool")
new_bool

array([ True,  True,  True])

## resize()

- istediğimzi bütün size'larda array üretebileceğimiz bir metoddur. Gerektiği zaman kendisi eleman ekler veya liste içerisinde yer alan elemanları silerek bizim istediğimiz boyutta bir array oluşturur

In [40]:
arr = np.array([[1, 3, 2],[4, 6, 5]])
arr

array([[1, 3, 2],
       [4, 6, 5]])

In [43]:
np.resize(arr, (2, 2))      # kullanmak istiyorsak bir değişkene atama yapmak zorundayız

array([[1, 3],
       [2, 4]])

In [44]:
np.resize(arr, (5, 2))

array([[1, 3],
       [2, 4],
       [6, 5],
       [1, 3],
       [2, 4]])

In [45]:
np.resize(arr, (7, 9))

array([[1, 3, 2, 4, 6, 5, 1, 3, 2],
       [4, 6, 5, 1, 3, 2, 4, 6, 5],
       [1, 3, 2, 4, 6, 5, 1, 3, 2],
       [4, 6, 5, 1, 3, 2, 4, 6, 5],
       [1, 3, 2, 4, 6, 5, 1, 3, 2],
       [4, 6, 5, 1, 3, 2, 4, 6, 5],
       [1, 3, 2, 4, 6, 5, 1, 3, 2]])

## arange ()

In [47]:
# sayılar üretir ve array döndürür

In [48]:
np.arange(1, 10, 3) # 1'den 9'a kadar. 3'er atlayarak

array([1, 4, 7])

In [49]:
np.arange(1, 8, 3)  

array([1, 4, 7])

In [50]:
np.arange(1, 10.1, 3)

array([ 1.,  4.,  7., 10.])

In [51]:
np.arange(10)   # 0'dan 9'a kadar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
np.arange(0, 10, 2)


array([0, 2, 4, 6, 8])

In [54]:
np.arange(0, 10, 2.2)

array([0. , 2.2, 4.4, 6.6, 8.8])

In [55]:
np.arange(0, -10, -2.2)

array([ 0. , -2.2, -4.4, -6.6, -8.8])

In [56]:
np.arange(0, 10, -2.2)

array([], dtype=float64)

## linspace()

In [57]:
# eşit aralıklı sayılar üretir

In [60]:
np.linspace(2, 3, 4)    # 2 ile 3 arasında 4 adet sayı üret. sayıların arasındaki mesafe aynı 

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [61]:
np.linspace(1, 10, 4)   

array([ 1.,  4.,  7., 10.])

In [62]:
np.linspace(1, 10, 5)   

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [63]:
np.linspace(1, 20)  # default değer 50 adettir. 

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

In [64]:
# NOT: Her zaman float sayılar döndürür.
# Veri görselleştirmede bolca kullanılacak.

In [65]:
np.linspace(1, 20, dtype=int)  # çok sağlıklı bir yöntem değildir

array([ 1,  1,  1,  2,  2,  2,  3,  3,  4,  4,  4,  5,  5,  6,  6,  6,  7,
        7,  7,  8,  8,  9,  9,  9, 10, 10, 11, 11, 11, 12, 12, 13, 13, 13,
       14, 14, 14, 15, 15, 16, 16, 16, 17, 17, 18, 18, 18, 19, 19, 20])

In [67]:
np.linspace(1, 10, 4, endpoint=True)    # default değerdir, bitiş noktasını dahil ederiz

array([ 1.,  4.,  7., 10.])

In [68]:
np.linspace(1, 10, 4, endpoint=False)   # bitiş noktasını dahil etmeyiz

array([1.  , 3.25, 5.5 , 7.75])

In [69]:
np.linspace(1, 20, 10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [73]:
np.linspace(1, 10, 4, retstep=False)   # default. Artış oranını göstermez

array([ 1.,  4.,  7., 10.])

In [75]:
np.linspace(1, 10, 4, retstep=True)   # Artış MİKTARINI belirtir (3.0)

(array([ 1.,  4.,  7., 10.]), 3.0)

## logspace()

* linspace ile kullanımı aynı

* logaritmik aralıklarda bir dizi oluşturur

* logaritmik tabandaki sayılarla işlem yapar

logaritmik tabanda 3 sayısı, 1000'e denk gelir, 4 sayısı, 10.000'e denk gelir

In [76]:
np.logspace(3, 4, num=4)

array([ 1000.        ,  2154.43469003,  4641.58883361, 10000.        ])

> default logaritmik taban 10'dur. yani log3 = 10^3 = 1000 yapmaktadır

In [77]:
np.logspace(2, 3, 5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

## zeros() & zeros_like()

- zeros() : belirtilen satır ve sütuna sahip olan 0'lardan oluşan bir matris array döndürür
- zeros_like() : mevcut bir array'in aynısından ama 0'lardan oluşan şekilde döndürür

In [80]:
np.zeros((4, 5))  # 0'lardan oluşan 4x5'lik bir matris döndürür. [Tuple içerisinde yazılır]

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [81]:
np.arange(1, 13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [82]:
arr2 = np.arange(1, 13).reshape(4, 3)
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [84]:
np.zeros_like(arr2) # bir önceki array integer ise bu da integer olur

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [85]:
np.zeros_like(arr2, dtype=bool)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

## ones() & ones_like()

In [86]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [88]:
np.ones_like(arr2)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [89]:
np.ones_like(arr2) * 4

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [90]:
np.ones_like(arr2) + 10

array([[11, 11, 11],
       [11, 11, 11],
       [11, 11, 11],
       [11, 11, 11]])

## eye()

- belirtilen boyutta bir birim matris oluşturur (identity matrix)

In [91]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [92]:
np.eye(4, k=1)  # öteleme yapar

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [93]:
np.eye(4, k=-2)  # öteleme yapar

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

## full() & full_like()

In [94]:
np.full((3, 3), 55, dtype=int)

array([[55, 55, 55],
       [55, 55, 55],
       [55, 55, 55]])

In [96]:
np.full((2, 5), 7)  # 2x5'lik bir array oluştur. elemanları hepsi 7 olsun

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [97]:
aa = np.full((2, 5), np.nan)
aa

array([[nan, nan, nan, nan, nan],
       [nan, nan, nan, nan, nan]])

In [99]:
aa.dtype        # numpy nan değeri her zaman float'tır

dtype('float64')