# **2. DERS: array(), Built in Function**

In [3]:
import numpy as np

## ndim ve ndmin 

ndim -> number of dimension
- oluşturulan array'in kaç boyutlu olduğunu gösterir

ndmin --> minimum dimension
- oluşturulan array'ın kaç boyutlu olacağını belirler

In [6]:
arr0 = np.array(5)
arr0

array(5)

In [5]:
arr0.ndim       # arr0 bir scaler'dir yani sıfır boyutludur

0

In [8]:
arr1 = np.array([1, 2])
arr1

array([1, 2])

In [9]:
arr1.ndim

1

In [11]:
my_list = list(range(0, 24))

In [13]:
my_array = np.array(my_list)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [14]:
my_array2 = np.array(my_list, ndmin=2)      # array'in 2 boyutlu olacağına karar verdik
my_array2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23]])

In [15]:
my_array2.ndim

2

In [18]:
my_array.shape      # tek boyutlu 

(24,)

In [19]:
my_array2.shape     # 2 boyutlu 

(1, 24)

## dtype and astype()

dtype
- oluşturduumuz array'ın taypını belirlediği gibi, göstermeye de yarar

astype()
- bir array'in type'ını değiştirir

In [20]:
# int8 -> 8bitlik bir integer'dır ve 1byte'a denk gelir.
# int64 -> 64bitlik bir integer'dır ve 8byte'a denk gelir.
# float128 -> 128bitlik bir float'tır ve 16byte'a denk gelir
# complex256
# uint16 

# vs vs...

In [21]:
my_int = np.array([1, 2, 3])
my_int

array([1, 2, 3])

In [22]:
my_int.dtype

dtype('int32')

In [23]:
my_int = np.array([1, 2, 3], dtype="int64")
my_int

array([1, 2, 3], dtype=int64)

In [24]:
my_float = np.array([1, 2, 3, 4.5])
my_float

array([1. , 2. , 3. , 4.5])

In [28]:
my_float.dtype

dtype('float64')

In [30]:
my_string = np.array(["emre", "çakır", 1, 2, 3, 5.2])
my_string   # hepsi string eleman'a dönüştü

array(['emre', 'çakır', '1', '2', '3', '5.2'], dtype='<U32')

In [31]:
my_string.dtype 

dtype('<U32')

In [33]:
my_float2 = np.array([1, 2, 3], dtype="float")
my_float2

array([1., 2., 3.])

In [35]:
my_float2.astype("int") # yeni bir değişkene atamalıyız

array([1, 2, 3])

In [36]:
my_float2

array([1., 2., 3.])

In [37]:
new_int = my_float2.astype("int")
new_int

array([1, 2, 3])

In [38]:
new_int.dtype

dtype('int32')

In [39]:
new_bool = my_float2.astype("bool")
new_bool

array([ True,  True,  True])

## resize()

- istediğimzi bütün size'larda array üretebileceğimiz bir metoddur. Gerektiği zaman kendisi eleman ekler veya liste içerisinde yer alan elemanları silerek bizim istediğimiz boyutta bir array oluşturur

In [40]:
arr = np.array([[1, 3, 2],[4, 6, 5]])
arr

array([[1, 3, 2],
       [4, 6, 5]])

In [43]:
np.resize(arr, (2, 2))      # kullanmak istiyorsak bir değişkene atama yapmak zorundayız

array([[1, 3],
       [2, 4]])

In [44]:
np.resize(arr, (5, 2))

array([[1, 3],
       [2, 4],
       [6, 5],
       [1, 3],
       [2, 4]])

In [45]:
np.resize(arr, (7, 9))

array([[1, 3, 2, 4, 6, 5, 1, 3, 2],
       [4, 6, 5, 1, 3, 2, 4, 6, 5],
       [1, 3, 2, 4, 6, 5, 1, 3, 2],
       [4, 6, 5, 1, 3, 2, 4, 6, 5],
       [1, 3, 2, 4, 6, 5, 1, 3, 2],
       [4, 6, 5, 1, 3, 2, 4, 6, 5],
       [1, 3, 2, 4, 6, 5, 1, 3, 2]])