# **3. DERS: concatenation & indexing**

## Variuous Built-in Methods

### rand() & randn() & randint()

- random.rand(): 0-1 aralığında üniform dağılıma sahip random float sayılar üretir
- random.randn(): ortalama değeri 0 ve std sapması 1 olan normal dağılıma sahip rastgele sayılar üretir
- random.randint(): belirtilen aralıkta rastgele tamsayılar üretir. Bitiş dahil değildir.

In [2]:
# random isimli kütüphaneyi çağırmaya gerek yok, numpy içerisinde var yukarıdaki metodlar

In [3]:
import numpy as np

#### rand()

In [4]:
np.random.rand()

0.017990522300247336

In [5]:
np.random.rand(2, 3)    # 2x3'lük bir array

array([[0.24426542, 0.05345968, 0.83407396],
       [0.28198723, 0.2330366 , 0.33761711]])

#### randn()

In [7]:
np.random.randn()

-1.1330260309329765

In [9]:
np.random.randn(3, 4)   # 3x4'lük bir array

array([[ 1.16381287, -1.71297701, -0.55503373,  0.5212252 ],
       [-0.74168577, -1.18680159, -0.2166399 , -1.86225507],
       [-0.05518285, -1.23266201,  0.32847299,  1.52733138]])

In [12]:
np.random.randn(120, 1521).mean() # 0'a yakın mean

0.002098071215882753

In [14]:
np.random.randn(120, 1521).std() # 1'e yakın std

1.0029135912184606

#### randint()

In [15]:
np.random.randint(10)   # default 0'dan başlar 10'a kadar, 10 dahil DEĞİL 

1

In [16]:
np.random.randint(4, 10)    # 4-10 arasında bir sayı

5

In [17]:
np.random.randint(1, 100, 8)    # 1-100 arasında 8 sayı (array-tek boyutlu)

array([41, 95, 66, 89, 79, 96, 59, 89])

In [19]:
np.random.randint(1, 100, size=(3, 2))  # 3x2 lik matrix

array([[98, 25],
       [ 6, 59],
       [95, 80]])

In [22]:
np.random.seed(42)
np.random.randint(1, 100, size=(3, 2))

# herkeste 42 numaralı seed içerisinde bulunan sabit rassal değerler kullanılır

array([[52, 93],
       [15, 72],
       [61, 21]])

### max() & argmax() & min() & argmin()

- argmin(): bir dizinin içindeki en küçük değerin indeksini döndürür
- argmax(): bir dizinin içindeki en büyük değerin indeksini döndürür