# **3. DERS: concatenation & indexing**

## Variuous Built-in Methods

### rand() & randn() & randint()

- random.rand(): 0-1 aralığında üniform dağılıma sahip random float sayılar üretir
- random.randn(): ortalama değeri 0 ve std sapması 1 olan normal dağılıma sahip rastgele sayılar üretir
- random.randint(): belirtilen aralıkta rastgele tamsayılar üretir. Bitiş dahil değildir.

In [2]:
# random isimli kütüphaneyi çağırmaya gerek yok, numpy içerisinde var yukarıdaki metodlar

In [3]:
import numpy as np

#### rand()

In [4]:
np.random.rand()

0.18807290780340502

In [5]:
np.random.rand(2, 3)    # 2x3'lük bir array

array([[0.11262783, 0.01842985, 0.62870335],
       [0.0936159 , 0.26722656, 0.00489425]])

#### randn()

In [6]:
np.random.randn()

0.597327128853519

In [7]:
np.random.randn(3, 4)   # 3x4'lük bir array

array([[-0.298154  , -1.37580139, -0.78291241,  2.13102934],
       [ 0.33041268, -0.65648416, -1.13822379,  0.48730469],
       [-0.41947501, -1.05783697,  0.2147453 ,  0.10734127]])

In [8]:
np.random.randn(120, 1521).mean() # 0'a yakın mean

0.002003911773943196

In [9]:
np.random.randn(120, 1521).std() # 1'e yakın std

0.9995084150314204

#### randint()

In [10]:
np.random.randint(10)   # default 0'dan başlar 10'a kadar, 10 dahil DEĞİL 

3

In [11]:
np.random.randint(4, 10)    # 4-10 arasında bir sayı

4

In [12]:
np.random.randint(1, 100, 8)    # 1-100 arasında 8 sayı (array-tek boyutlu)

array([75, 30, 70, 46, 81, 54, 46, 11])

In [13]:
np.random.randint(1, 100, size=(3, 2))  # 3x2 lik matrix

array([[99, 65],
       [26, 94],
       [88, 26]])

In [14]:
np.random.seed(42)
np.random.randint(1, 100, size=(3, 2))

# herkeste 42 numaralı seed içerisinde bulunan sabit rassal değerler kullanılır

array([[52, 93],
       [15, 72],
       [61, 21]])

### max() & argmax() & min() & argmin()

- argmin(): bir dizinin içindeki en küçük değerin indeksini döndürür
- argmax(): bir dizinin içindeki en büyük değerin indeksini döndürür

In [15]:
my_array1 = np.random.randint(0, 50, 12)
my_array1

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2, 21,  1])

In [16]:
my_array1.min()

1

In [17]:
my_array1.max()

39

In [18]:
my_array1.argmin()  # index değeridir

11

In [19]:
my_array1.argmax()  # index değeridir

7

## size

In [20]:
# bir array'deki eleman sayısını gösterir. 
# 2x4'lük matris için size=8'dir

In [21]:
aa = my_array1.reshape(-1, 4)
aa

array([[38, 18, 22, 10],
       [10, 23, 35, 39],
       [23,  2, 21,  1]])

In [22]:
aa.reshape(-1, 4).size

12

In [23]:
len(aa) # len() array'ın satır sayısını verir

3

## itemsize

In [24]:
# bir verinin bellekte kapladığı miktarın değerini verir bize

In [25]:
aa

array([[38, 18, 22, 10],
       [10, 23, 35, 39],
       [23,  2, 21,  1]])

In [26]:
aa.itemsize     # çıktıda byte sayısı vardır. her bir değerin byte'dır. Yani 12 tane 4 byte var

4

In [27]:
aa.dtype

dtype('int32')

In [28]:
aa.itemsize * aa.size   # toplam kapladığı alandır 

48

## copy()

In [29]:
# array'ın kopyasını almamızı sağlar

In [30]:
my_array2 = np.arange(1, 17).reshape(-1, 4)
my_array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [31]:
my_array2_copy = my_array2.copy()   # artık tüm işlemleri bu kopya üzerinden yapabiliriz
my_array2_copy      

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

## transpose()

In [32]:
my_array2_copy

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [33]:
my_array2_copy.transpose()  # T harfini kullanabailiriz. Bir sonraki hücreye bak:

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [34]:
my_array2_copy.T

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

## Concatenation of the Arrays (array'ları birleştirme)

- axis bizim eksenimiz olacak.
- axis=0, row bazında birleştir (dikey birleştirme)
- axis=1, column bazında birleştir (yatay birleştirme)
    - yani axis=0, row sayısını artırırken; axis=1, column sayısını artırır

- NOT: Tek boyutlu olan array'lerde her zaman yan yana ekleme yapar. Örnekle daha anlaşılır oluyor

In [35]:
x = np.arange(1, 7) # tek boyutlu
x

array([1, 2, 3, 4, 5, 6])

In [36]:
y = np.arange(7, 14) # tek boyutlu
y

array([ 7,  8,  9, 10, 11, 12, 13])

In [37]:
xy = np.concatenate((x, y))  # tek boyutlu birleştirme
xy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [38]:
# matrislerde:

a = np.array([[1, 2], [3, 4]])  # 2x2 matrix
a

array([[1, 2],
       [3, 4]])

In [39]:
b = np.array([[5, 6], [7, 8]])  # 2x2 matrix
b

array([[5, 6],
       [7, 8]])

In [40]:
ab = np.concatenate((a, b)) # default -> axis=0 {alt alta eklenir, row sayısı değişir}
ab

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [41]:
ab = np.concatenate((a, b), axis=1) # axis=1 {yan yana eklenir, column sayısı değişir}
ab
ab

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [42]:
a = np.array([[1, 2], [3, 4]])  # 2x2 matrix
a

array([[1, 2],
       [3, 4]])

In [43]:
b = np.array([[5, 6], [7, 8], [9, 10]])  # 3x2 matrix
b

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [44]:
np.concatenate((a, b), axis=0)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [45]:
#np.concatenate((a, b), axis=1) ---> hata verir

In [46]:
np.concatenate((a, b), axis=None)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
#NOT: eğer axis=None dersek, bütün elemanları yan yana yazıp tek boyuta indirir

## Splitting of the Arrays (array'ları ayrıştırma)

- split(): belirtilen eksende eşit parçalara böler
    * eğer çift sayıda eleman sayısı yoksa eşit parçaya bölemez
- array_split(): belirtilen sayıda ama eşit olmayan parçalara böler
- vsplit(): bir diziyi yeni satırlar üzerindne birden çok parçaya ayırır
- hsplit(): yeni sutunlar üzerinden birçok parçaya ayırır

In [48]:
my_array3 = np.arange(1, 9)
my_array3

array([1, 2, 3, 4, 5, 6, 7, 8])

In [49]:
np.split(my_array3, 2)

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]

In [50]:
np.split(my_array3, 4)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

In [ ]:
#np.split(my_array3, 5) ---> hata verir. 8 elemanı 5'e eşit ayıramazsın

In [51]:
np.array_split(my_array3, 5) 

[array([1, 2]), array([3, 4]), array([5, 6]), array([7]), array([8])]

In [52]:
np.split(my_array3, [5]) # ---> 5. indexten iki parçaya ayırır

[array([1, 2, 3, 4, 5]), array([6, 7, 8])]

In [53]:
np.split(my_array3, [2]) # ---> 2. indexten iki parçaya ayırır

[array([1, 2]), array([3, 4, 5, 6, 7, 8])]

In [54]:
aa = np.arange(1, 18)
aa

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [55]:
np.split(aa, [5])

[array([1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])]

In [56]:
np.split(aa, [5, 8])    # ---> 5. ve 8. indexler'den böler

[array([1, 2, 3, 4, 5]),
 array([6, 7, 8]),
 array([ 9, 10, 11, 12, 13, 14, 15, 16, 17])]

In [57]:
my_array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [58]:
np.split(my_array2, [1], axis=0) # default değerdir yazmasan da olur. 

[array([[1, 2, 3, 4]]),
 array([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [59]:
np.split(my_array2, [1], axis=1) # 1. kolon'u aldı, geri kalanını olduu gibi yazdırdı

[array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2,  3,  4],
        [ 6,  7,  8],
        [10, 11, 12],
        [14, 15, 16]])]

## Sorting of Arrays

In [60]:
bb = np.array([2, 4, 1, 5, 3])
bb

array([2, 4, 1, 5, 3])

In [61]:
np.sort(bb) # kalıcı değildir               

array([1, 2, 3, 4, 5])

In [62]:
bb  

array([2, 4, 1, 5, 3])

In [63]:
bb.sort()      # kalıcıdır

In [64]:
bb

array([1, 2, 3, 4, 5])

In [65]:
my_array4 = np.random.randint(5, 50, (3, 3))
my_array4

array([[28, 48, 34],
       [42,  6, 25],
       [37, 16, 26]])

In [66]:
np.sort(my_array4)

array([[28, 34, 48],
       [ 6, 25, 42],
       [16, 26, 37]])

In [69]:
np.sort(my_array4, axis=1)  # default değerdir[satırları ayrı ayrı sıralar]

array([[28, 34, 48],
       [ 6, 25, 42],
       [16, 26, 37]])

In [70]:
np.sort(my_array4, axis=0)  # kolonlar içerisinde bir sort işlemi yapar

array([[28,  6, 25],
       [37, 16, 26],
       [42, 48, 34]])

In [73]:
np.sort(my_array4, axis=None)   # tek boyuta, yani vektöre çevirir (Sıralanmış halde)

array([ 6, 16, 25, 26, 28, 34, 37, 42, 48])

## axis ile ilgili örnek

In [74]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [75]:
arr1.ndim

1

In [76]:
arr1.shape

(3,)

In [77]:
# vektörlerde görüldüğü gibi tek bir axis vardır. O yüzden de yan yana concatenate olur.

np.concatenate((arr1, arr2))

array([1, 2, 3, 4, 5, 6])

In [78]:
arr3 = np.array([[1,2],[3,4]])
arr4 = np.array([[5,6],[7,8]])

In [79]:
arr3.ndim

2

In [80]:
arr3.shape

(2, 2)

In [81]:
np.concatenate((arr3, arr4), axis=0)    

# arr4'ü arr3'ün altına ekler ve row sayısı artmış olacak

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.concatenate((arr3, arr4), axis=1)    

# arr4'ü arr3'ün yanına ekler ve column sayısı artmış olacak